# Hexapod configuration Settings


# Define leg measurements in meters
COXA_LENGTH:   0.0330
FEMUR_LENGTH:  0.0900
TIBIA_LENGTH:  0.1125

# Body standing Height
STANDING_BODY_HEIGHT: 0.06

# Body sitting Height
SITTING_BODY_HEIGHT: 0.01

# Leg lift height is the max distance in meters the foot is lifted off the ground in a full step ( Gait Settings )
# If you set this to close to the total measurement of your femur and tibia the leg IK calculation might fail
LEG_LIFT_HEIGHT: 0.02

# Distance per gait period
GAIT_PERIOD_DISTANCE: 0.12

# Define vector x & y component in meters in the local coordinate system from center of the hexapod platform to coxa joint ['LF', 'LM', 'LB', 'RF', 'RM', 'RB']
CENTER_TO_COXA_X: [-0.055, -0.085, -0.055, 0.055, 0.085, 0.055]
CENTER_TO_COXA_Y: [0.076, 0.0, -0.076, 0.076, 0.0, -0.076]

# Define vector x & y component in meters from origin in the global coordinate system to feet ground contact joint ['LF', 'LM', 'LB', 'RF', 'RM', 'RB']
CENTER_TO_FEET_X: [-0.1114, -0.18, -0.1114, 0.1114, 0.18, 0.1114]
CENTER_TO_FEET_Y: [0.1539, 0.0, -0.1539, 0.1539, 0.0, -0.1539]
CENTER_TO_FEET_Z: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

# Define the lower and upper bounds for parameters in the translate & rotate mode.
PITCH_LOWER_BOUND: -0.25
PITCH_UPPER_BOUND: 0.25

YAW_LOWER_BOUND: -0.25
YAW_UPPER_BOUND: 0.25

ROLL_LOWER_BOUND: -0.4
ROLL_UPPER_BOUND: 0.4

POSITION_X_LOWER_BOUND: -0.04
POSITION_X_UPPER_BOUND: 0.04

POSITION_Y_LOWER_BOUND: -0.04
POSITION_Y_UPPER_BOUND: 0.04
